PRINT_ALPACA: false
EMAIL_REPORTER: false
APPLY_FIXES: all

# Lint specifig settings
ENABLE: [BASH, MARKDOWN, CREDENTIALS]

BASH_SHFMT_ARGUMENTS: -i 2
BASH_SHFMT_FILE_EXTENSIONS: [.sh, .bash, .bats]
BASH_SHELLCHECK_FILE_EXTENSIONS: [.sh, .bash, .bats]
COPYPASTE_JSCPD_ARGUMENTS: --ignore "bash/lib,report"
