---
name: Conform DCO (--Sign-off)
on: [workflow_call] # yamllint disable-line rule:truthy

jobs:
  signoff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
        if: github.event_name == 'pull_request'
      
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
        if: github.event_name != 'pull_request'

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
        if: github.event_name == 'pull_request'
        
      - name: Setup main branch without switching current branch
        if: github.event_name == 'pull_request'
        run: git fetch origin main:main

      - name: Conform Action
        uses: docker://ghcr.io/siderolabs/conform:v0.1.0-alpha.27-2-g7d9dec0
        with:
          args: "enforce --base-branch=main"
