---
name: Conform DCO (--Sign-off)
on: [workflow_call] # yamllint disable-line rule:truthy

jobs:
  signoff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Conform Action
        run: |
          ./scripts/check-code-quality.sh
