name: Bats test

on: [workflow_call] # yamllint disable-line rule:truthy

jobs:
  run-bats-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 7

      - name: Download bats and run tests
        run: |
          git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.11.3
          . "$HOME/.asdf/asdf.sh"
          asdf plugin add semver
          asdf install semver latest
          asdf global semver latest
          asdf plugin add git-chglog
          asdf install git-chglog latest
          asdf global git-chglog latest
          bash/install_bats.bash
          bash/lib/bats/bin/bats --print-output-on-failure --show-output-of-passing-tests --verbose-run bash/src/test
